name: Code for San Francisco
url: http://alpha.codeforsanfrancisco.org
title: Code for San Francisco
description: "San Francisco's weekly event to build, share, and learn about civic tech"
encoding: utf-8
timezone: America/Los_Angeles
permalink: pretty

google_api_key: AIzaSyASGyuTdO6QCoVBaKSK360IWdpVpmGiqow
google_analytics: UA-70064412-5

# development key
# google_api_key: AIzaSyBrSPsoJXo-iI97sUWEjIhDdCqUkghScQk

github: sfbrigade/alpha.codeforsanfrancisco.org
twitter: sfbrigade
facebook: codeforsanfrancisco
youtube: UCLFcPyza0fGFEDMEb1A14XQ
meetup: Code-for-San-Francisco-Civic-Hack-Night
mailchimp: http://eepurl.com/bfFkF9

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "events"
    values:
      layout: "event"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - scripts
  - vendor/bundle/
  - yarn.lock

future: true

logo: /img/logo.png

collections:
  events:
    output: true

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
