name: Code for San Francisco
url: http://codeforsanfrancisco.org
title: Code for San Francisco
description: "San Francisco's weekly event to build, share, and learn about civic tech"
encoding: utf-8
timezone: America/Los_Angeles
permalink: pretty

google_api_key: AIzaSyASGyuTdO6QCoVBaKSK360IWdpVpmGiqow
google_analytics: UA-70064412-5

# development key
# google_api_key: AIzaSyBrSPsoJXo-iI97sUWEjIhDdCqUkghScQk

github: sfbrigade/alpha.codeforsanfrancisco.org
twitter: sfbrigade
facebook: codeforsanfrancisco
youtube: UCLFcPyza0fGFEDMEb1A14XQ
meetup: Code-for-San-Francisco-Civic-Hack-Night
mailchimp: http://eepurl.com/bfFkF9
slack_org: https://sfbrigade.slack.com

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "events"
    values:
      layout: "event"
  - scope:
      type: projects
    values:
      layout: project

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - scripts
  - vendor/bundle/
  - yarn.lock

future: true

logo: /img/logo.png

collections:
  events:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
